# Generated by Django 6.0.3 on 2026-03-30 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อเมนู')),
                ('price', models.IntegerField(verbose_name='ราคา')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='รูปภาพอาหาร')),
                ('is_available', models.BooleanField(default=True, verbose_name='พร้อมขาย (มีของ)')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'รอเข้าใช้งาน'), ('completed', 'สำเร็จ (ทานเสร็จแล้ว)'), ('cancelled', 'ยกเลิกการจอง')], default='pending', max_length=20, verbose_name='สถานะการจอง'),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'ว่าง / พร้อมใช้งาน'), ('maintenance', 'ปรับปรุง / ซ่อมแซม'), ('closed', 'ปิดให้บริการ')], default='available', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='จองเมื่อ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่จอง'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(blank=True, null=True, verbose_name='จำนวนคน'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.table', verbose_name='โต๊ะที่จอง'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลา'),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='หมายเลขโต๊ะ'),
        ),
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.IntegerField(default=4, verbose_name='จำนวนที่นั่ง'),
        ),
    ]
