# Generated by Django 6.0.3 on 2026-03-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อผู้จอง')),
                ('phone', models.CharField(max_length=15, verbose_name='เบอร์ติดต่อ')),
                ('date', models.DateField(verbose_name='วันที่จอง')),
                ('time', models.TimeField(verbose_name='เวลาที่จอง')),
                ('guests', models.IntegerField(verbose_name='จำนวนคน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='จองเมื่อ')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='เลขโต๊ะ (เช่น A1, B2)')),
                ('seats', models.IntegerField(verbose_name='จำนวนที่นั่ง')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
        ),
    ]
